# Generated by Django 5.0.6 on 2024-08-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zlauth", "0002_alter_captchamodel_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchamodel",
            name="captcha",
            field=models.CharField(max_length=20),
        ),
    ]
